### ISSUE TITLE
Frequency doesn't change on channel 2

### ISSUE THREAD

**Issue by HoRaMusic** [MajicDesigns/MD_SN76489#1]
Hello, 

I've noticed than the frequency of the channel 2 doesn't change.
This seems to come from  MD_SN76489.cpp
In `setFrequency(uint8_t chan, uint16_t freq)` the condition` if (chan < MAX_CHANNELS - 2)`
probably need to be fixed like this :` if (chan < MAX_CHANNELS - 1)`

**Comment by MajicDesigns** [comment]
You're probably correct. Have you tried changing as per your suggestion and did it fix your problem?

**Comment by HoRaMusic** [comment]
Yes, tested (on stm32f103)  and it fixes the problem.

**Comment by HoRaMusic** [comment]
Something interesting for the lib could be to use timer interrupt instead of millis() and use GPIO register for fast writing of the data bytes (but this is different for every board).

**Comment by MajicDesigns** [comment]
I have no interest in that aspect as it would mean a different version for the many hardware types with the ensuing support issues and requests to support 'hardware X' because that is what the requester has. The code in the lib should be enough for anyone else with interest and with skills to  to get their own interrupt enabled version running.

BTW, if you used this on the STM32, did you implement the SN76489 clock in software? If so, can you contribute that back for others to use as well?

**Comment by MajicDesigns** [comment]
Fixed. Released as v1.1.1

**Comment by HoRaMusic** [comment]
Sorry, for the delay, 
I understand you point of view.
Concerning the clock I'ising a 4Mhz crystal.
